<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/osmformat.proto

namespace osm2sql\pbf;

if (false) {
    /**
     * This class is deprecated. Use osm2sql\pbf\Relation\MemberType instead.
     * @deprecated
     */
    class Relation_MemberType {}
}
class_exists(Relation\MemberType::class);
@trigger_error('osm2sql\pbf\Relation_MemberType is deprecated and will be removed in the next major release. Use osm2sql\pbf\Relation\MemberType instead', E_USER_DEPRECATED);

