<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/osmformat.proto

namespace Osm2sql\Pbf\Relation;

use Osm2sql\Pbf\Relation_MemberType;
use UnexpectedValueException;

/**
 * Protobuf type <code>Osm2sql.Pbf.Relation.MemberType</code>
 */
class MemberType
{
    /**
     * Generated from protobuf enum <code>NODE = 0;</code>
     */
    const NODE = 0;
    /**
     * Generated from protobuf enum <code>WAY = 1;</code>
     */
    const WAY = 1;
    /**
     * Generated from protobuf enum <code>RELATION = 2;</code>
     */
    const RELATION = 2;

    private static $valueToName = [
        self::NODE => 'NODE',
        self::WAY => 'WAY',
        self::RELATION => 'RELATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MemberType::class, Relation_MemberType::class);

