<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/fileformat.proto

namespace GPBMetadata\Resources;

use Google\Protobuf\Internal\DescriptorPool;

class Fileformat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0010a1a7265736f75726365732f66696c65666f726d61742e70726f74" .
            "6f120b6f736d3273716c2e706266226c0a04426c6f62120b0a0372617718" .
            "012001280c12100a087261775f73697a6518022001280512110a097a6c69" .
            "625f6461746118032001280c12110a096c7a6d615f646174611804200128" .
            "0c121f0a134f42534f4c4554455f627a6970325f6461746118052001280c" .
            "42021801223f0a0a426c6f62486561646572120c0a047479706518012001" .
            "280912110a09696e6465786461746118022001280c12100a086461746173" .
            "697a65180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

